# Generated by Django 4.2.11 on 2024-07-16 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_app', '0002_taskitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='user',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
